#!/bin/dash
CURR_THEME=$(cat ~/.config/gtk-3.0/settings.ini | grep gtk-theme-name | cut -c 16-)
printf "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>
<openbox_pipe_menu xmlns=\"http://openbox.org/\"
	xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
	xsi:schemaLocation=\"http://openbox.org/\" >
	<separator label=\"Current: $CURR_THEME\" />"
ls -1 /usr/share/themes |
	while read theme; do
		printf "	<item label=\"$theme\">
		<action name=\"Execute\">
			<command>dash ~/.config/openbox/scripts/switchtheme gtk-theme-name \"$theme\"</command>
		</action>
	</item>\n";
	done
printf "</openbox_pipe_menu>"
