#!/bin/dash
if ! pkexec apt-get update; then
	notify-send Openbox "This operation must be run as root."
	exit 1
fi
RESULT=$(apt-get -q -y --ignore-hold --allow-change-held-packages --allow-unauthenticated -s dist-upgrade | /bin/grep  ^Inst | wc -l)
if [ "$RESULT" = "0" ]; then
	notify-send Openbox "Everything up to date."
fi
