#!/bin/bash

command=$1

if [ "$command" = "" ]; then
    echo "usage: $0 {up|down|toggle}"
    exit 0;
fi

if [ "$command" = "up" ]; then
    pactl -- set-sink-volume 0 +5%
fi

if [ "$command" = "down" ]; then
    pactl -- set-sink-volume 0 -5%
fi

if [ "$command" = "toggle" ]; then
	pactl set-sink-mute 0 toggle
	if ! pacmd list-sinks | grep "muted: no" > /dev/null; then
		notify-send "Volume: Muted"
	else
		notify-send "Volume: Unmuted"
	fi
	exit
fi

notify-send "Volume: $(pactl list sinks | grep '^[[:space:]]Volume:' | \
    head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')%"
